### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [AequilibraE/qaequilibrae#1]
Installing the plugin does not work on my Linux Mint 17(=Ubuntu 14.04) with QGIS 2.16.2 installed:
Error on first try:
**numpy.dtype has the wrong size, try recompiling**
Error when just repeating:
**cannot import name _one_to_all**

**Comment by pedrocamargo** [comment]
Hi Bernd,

The the problem is the Numpy version you have in that machine (it is older
than the one I used to compile it).

There are two solutions. Update Numpy or recompile AequilibraE's Cython
code.

To update your numpy installation you can do the following on your terminal:

sudo apt-get install python-pip
sudo pip install numpy --upgrade

If you prefer to re-compile the Cython code just let me know and I'll send
the instructions.  It has a few more steps and you would have to do that
every time you want to get a new version of AequilibraE.

Cheers,
Pedro

On Sep 15, 2016 1:21 AM, "Bernd-Vogelgesang" notifications@github.com
wrote:

Installing the plugin does not work on my Linux Mint 17(=Ubuntu 14.04) with
QGIS 2.16.2 installed:
Error on first try:
_numpy.dtype has the wrong size, try recompiling_
Error when just repeating:
_cannot import name _one_to_all_

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/AequilibraE/AequilibraE/issues/1, or mute the thread

**Comment by Bernd-Vogelgesang** [comment]
Hi Pedro,
thanks a lot for the instructions.
I'll try to update numpy then. Great that you provided the code!
Cheers
Bernd

**Comment by pedrocamargo** [comment]
Let me know how it goes so we know this is a good solution for other users
in the future.

Cheers,
Pedro
